### PR TITLE
submissions from Team UW

### PR DESCRIPTION
**Pull request by mobehbooei**
Hi, this is the pull request from Team UW.
I have submitted the results for Germany and Netherlands data sets.

### CODE REVIEW

**Comment by raoulcollenteur** [comment]
Hi @mobehbooei. Thanks for the submission. Before merging, could you please make the following changes to the submission?

- could you revert the changes made to the original data, all submitted files should be contained within your submission folder. Also please remove the .vs folder from the PR.
- the reported development time seems not realistic. Please provide an (rough) estimate of the time it took to develop the models (e.g., read in data, pick a model structure, etcetera).

Cheers,

Raoul

**Comment by mobehbooei** [comment]
Thanks
As for development time, that was my misunderstanding. I thought you mean training time. I will correct it.

**Comment by mobehbooei** [comment]
Is everything ok now?

**Review by raoulcollenteur — APPROVED** [review]

**Comment by raoulcollenteur** [comment]
Hi @mobehbooei ! All looks good now so I will merge the PR. Thanks for the submission!

Cheers,
Raoul

**Pull request merged**
